(deftheme panda-seti
  "Created 2016-12-01.")

(custom-theme-set-faces
 'panda-seti
 '(default ((t (:family "Monaco" :foundry "nil" :width normal :height 141 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#D4D7D6" :background "#151718" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#151718" :background "SkyBlue2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#4F99D3"))))
 '(highlight ((t (:background "##F0F0F0"))))
 '(region ((t (:background "#434546"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#1E2326"))))
 '(trailing-whitespace ((t (:background "#41535B"))))
 '(font-lock-builtin-face ((t (:foreground "#A074C4"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#41535B"))))
 '(font-lock-constant-face ((t (:foreground "#CE4045"))))
 '(font-lock-doc-face ((t (:foreground "#55B5DB"))))
 '(font-lock-function-name-face ((t (:foreground "#55B5DB"))))
 '(font-lock-keyword-face ((t (:foreground "#9FCA56"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#55B5DB"))))
 '(font-lock-type-face ((t (:foreground "#DCCD69"))))
 '(font-lock-variable-name-face ((t (:foreground "#55B5DB"))))
 '(font-lock-warning-face ((t (:weight bold :inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#2F3C42" :background "#0D1011"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color "Black" :style nil) :foreground "gray60" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "yellow" :background "Black" :inherit nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 3 :color "#4F99D3" :style nil)))))
 '(mode-line-inactive ((t (:weight light :slant italic :box (:line-width -3 :color "black" :style nil) :foreground "gray60" :background "Black"))))
 '(isearch ((t (:weight bold :foreground "#161616" :background "#87ceeb"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight bold :foreground "#161616" :background "#4f94cd"))))
 '(match ((t (:weight bold :foreground "#151718" :background "#8BE03C"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'panda-seti)
